# GitLab CI 템플릿 - Jenkins 빌드 자동 트리거
# 각 프로젝트의 .gitlab-ci.yml에 추가

# 필요한 CI/CD Variables:
# - JENKINS_URL: Jenkins 서버 URL (예: https://jenkins.example.com)
# - JENKINS_USER: Jenkins 사용자 ID
# - JENKINS_API_TOKEN: Jenkins API 토큰
# - BUILD_TOKEN: Jenkins 빌드 트리거 토큰 (각 job에서 설정)

stages:
  - build
  - trigger

# 기존 빌드 스테이지들...

# Jenkins 빌드 트리거 (main 브랜치 머지 시)
trigger_jenkins_main:
  stage: trigger
  image: curlimages/curl:latest
  script:
    - |
      echo "Triggering Jenkins build for $CI_PROJECT_NAME..."
      curl -X POST \
        "$JENKINS_URL/job/$CI_PROJECT_NAME-build/build?token=$BUILD_TOKEN" \
        --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
        --silent --show-error
      echo "Jenkins build triggered successfully"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
  tags:
    - docker

# Jenkins 빌드 트리거 (pre-release 브랜치 머지 시)
trigger_jenkins_prerelease:
  stage: trigger
  image: curlimages/curl:latest
  script:
    - |
      echo "Triggering Jenkins build for $CI_PROJECT_NAME (pre-release)..."
      curl -X POST \
        "$JENKINS_URL/job/$CI_PROJECT_NAME-build/build?token=$BUILD_TOKEN" \
        --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
        --silent --show-error
      echo "Jenkins build triggered successfully"
  rules:
    - if: '$CI_COMMIT_BRANCH == "pre-release" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
  tags:
    - docker

# Slack 알림 (선택사항)
notify_slack:
  stage: trigger
  image: curlimages/curl:latest
  script:
    - |
      curl -X POST \
        -H 'Content-type: application/json' \
        --data "{\"text\":\"[GitLab] $CI_PROJECT_NAME 빌드 트리거됨 (브랜치: $CI_COMMIT_BRANCH)\"}" \
        "$SLACK_WEBHOOK_URL"
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(main|pre-release)$/ && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
  allow_failure: true
  tags:
    - docker
